FROM node:20-bookworm-slim
RUN apt update && \
    apt install -y imagemagick
RUN sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml
WORKDIR /app
