server {
    listen 80 default;
    listen [::]:80;

    server_name afonso.dev.localhost;

    add_header X-Docker-Container "fns-nginx";

    root /app/dist;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location ~* ^/(.*)/$ {
        try_files /$1/index.html /$1.html =404;
    }

    error_page 404 /404.html;
    error_page 403 /404.html;
}
