name: Build and Deploy to Cloudflare Pages

on:
  schedule:
    - cron: '0 3 1 * *' # At 03:00 on day-of-month 1
  push:
    branches:
      - main
      - develop
      - oven

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: afonsodemori/afonso-dev:latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set CACHE_HASH
        run: echo "CACHE_HASH=$(echo ${GITHUB_SHA} | head -c7)" >> $GITHUB_ENV

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ env.CACHE_HASH }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Dependencies
        run: make ci

      - name: Install Assets
        run: make assets
        env:
          CACHE_HASH: ${{ env.CACHE_HASH }}

      - name: Generate Pages
        run: make pages
        env:
          CACHE_HASH: ${{ env.CACHE_HASH }}

      - name: Generate Shortcuts
        run: make shortcuts

      - name: Import Resumes
        run: make resumes

      - name: Create Health Check File
        run: |
          {
            echo '<!DOCTYPE html><html lang="en">'
            echo '<head><meta name="viewport" content="width=device-width, initial-scale=1"><title>Health Check</title></head>'
            echo '<body>'
            echo '<h1>OK</h1>'
            echo "<p>${GITHUB_REF##*/}@${CACHE_HASH}</p>"
            echo "<address>$(date)</address>"
            echo '</body></html>'
          } > dist/health-check.html

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: afonso
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
