name: Build and deploy Pages

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "10 0 1 * *"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Install dependencies
#        uses: php-actions/composer@v6
#        with:
#          php_version: "8.1"
#          version: 2.x

      - name: Install assets
        run: bin/install-assets

      - name: Generate shortcuts
        run: bin/generate-shortcuts

      - name: Import CV from Google Drive
        run: bin/import-cv

      - name: Generate pages
        run: bin/generate-pages

      - name: Move generated files
        run: |
          echo "<h1>OK</h1>" > dist/health-check.html
          echo "<address>Last build: $(date)</address>" >> dist/health-check.html

      - name: Upload artefact
        uses: actions/upload-pages-artifact@v1

  deploy:
    needs: build
    environment:
      name: github-pages
      url:
        ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
