name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - develop
      - oven

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: afonsodemori/afonso-dev:latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: make ci

      - name: Install assets
        run: make assets

      - name: Generate pages
        run: make pages

      - name: Generate shortcuts
        run: make shortcuts

      - name: Import resumes
        run: make resumes

      - name: Tag with version
        run: |
          {
            echo '<!DOCTYPE html><html lang="en">'
            echo '<head><meta name="viewport" content="width=device-width, initial-scale=1"><title></title></head>'
            echo '<body>'
            echo '<h1>OK</h1>'
            echo "<p>${GITHUB_REF##*/}@$(echo ${GITHUB_SHA} | head -c7)</p>"
            echo "<address>$(date)</address>"
            echo '</body></html>'
          } > dist/health-check.html

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: afonso
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
